name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses:  dtolnay/rust-toolchain@stable

#      - name: Lint
#        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --release
